---
# handlers file for haproxy
- name: restart haproxy
  service: name=haproxy state=restarted

- name: test config and restart haproxy
  command: /usr/sbin/haproxy -f {{ config_location }} -c
  register: command_result
  failed_when: command_result.rc != 0
  notify: restart haproxy

- name: 'Assemble the final configuration file'
  assemble: src={{ etc_prefix }}/haproxy/conf.d dest={{ config_location }} backup=yes
  notify: test config and restart haproxy
  tags: 'test'
